### ISSUE TITLE
Error while  compiling the code with all versions of Arduino

### ISSUE THREAD

**Issue by pradipkhare** [marcmerlin/NewLiquidCrystal#1]
Hi,
First of all thank you very much for providing the all libraries under the folder NewLiquidCrystal. It seems to be very helpful person like, who wants to use Serial Display for the LCD. However, I am facing a fatal issue while compiling the code (your example in I2C_new.pde). I have tried to compile using in all Arduino IDEs starting from version from 1.5 back to 1.0 in all possible ways and getting following compilation error in all of them:-

"I2C_New.cpp.o: In function '_static_initialization_and_Destruction_o': error in I2C_New.cpp: 7: undefined reference to 'LiquidCrystal_I2C::LiquidCrystal_I2C(unsigned char)'." 
This error is comming in all versions (which I installed, complied the code and then uninstalled for the lower version, hoping that it may compile there. I am unable to proceed further), pls provide your  expert help in this and will highly appreciate the same. I haven't done any changes in your code and just copy pated took it as it is. Also, before reaching to you, I have done all due diligence from my side to compile it, however no luck. 

I am attaching following images for your help:-
1) Error that I am getting
2) Structure of the code including libraries

Regards,
Pradip

![CompilationError](https://f.cloud.github.com/assets/3107733/29510/dc3ff412-4d8d-11e2-96c7-20b77a810901.jpg)

![File_Structure](https://f.cloud.github.com/assets/3107733/29508/bc8c206e-4d8d-11e2-98e7-ca267a1540dc.jpg)

**Comment by marcmerlin** [comment]
Due to some unknown problem, I never got notification for this issue, my apologies.
I actually never worked with the I2C code, I only worked on the Shift Register (_SR) code. You should try the upstream project for I2C issues: https://bitbucket.org/fmalpartida/new-liquidcrystal/wiki/Home

I'm closing this because sadly I can't help you with the I2C part of the code I didn't write and never used.
